version: '3.8'

services:
  mongodb:
    image: 'mongodb/mongodb-community-server:7.0.7-ubi8'
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
